GET {{URL}}:{{PORT}}

###
@USER_EMAIL=mario@example.com
@USER_PASS=12341234

POST {{URL}}:{{PORT}}/{{API_AUTH}}/login
Content-Type: application/json

{
	"email": "{{USER_EMAIL}}",
	"password": "{{USER_PASS}}"
}

###

DELETE {{URL}}:{{PORT}}/{{API_AUTH}}/logout
